### ISSUE TITLE
Syntax is lost when hitting TAB for auto completion fails

### ISSUE THREAD

**Issue by FreddieOliveira** [zdharma/fast-syntax-highlighting#192]
If I start typing something and hit Tab to complete, but it can't complete with anything the whole line syntax is lost. May be related to #189.

To reproduce, type:

![Screenshot_20200620-193135_Termux](https://user-images.githubusercontent.com/9597536/85212793-e556ae80-b345-11ea-8948-959a7e42c297.png)

Then hit TAB

![Screenshot_20200620-193203_Termux](https://user-images.githubusercontent.com/9597536/85212810-015a5000-b346-11ea-947e-c8d762420987.png)

**Comment by pushqrdx** [comment]
@FreddieOliveira  spent few hours trying to debug that as i really like the accuracy of this plugin over `zsh-syntax-highlighting` i believe i fixed it, can you give the pr a test?

**Comment by FreddieOliveira** [comment]
Wow, thanks @pushqrdx, your PR indeed fixed the bug. I was already learning to live with it, but now we can be colorful again!

**Comment by hexchain** [comment]
Would you please reopen this, since #198 is now reverted?

Also, to maintainer: is 199 the reason for the revert?

**Comment by FreddieOliveira** [comment]
Yes, indeed the issue is back. @psprint Why exactly was the PR reverted without any explanation? Was it causing any side effects?

**Comment by NICHOLAS85** [comment]
It seems the PR removed a line which was added in eb717724c1d2caaa52c2a325521d369b25284dac for #8. Maybe it was reverted to not break the earlier issue.

**Comment by FreddieOliveira** [comment]
@NICHOLAS85 No, that's not the case. I use zsh with vi mode and this plugin checked out in 52bd0950886102ec8cb9a1624eb0fb0566505abd and I can't reproduce the issue you referenced. In fact it's been half a year I don't upgrade the plugin and I've never faced any problems with @pushqrdx PR, which makes a never solved mystery on why the PR was reverted.

Also, this current issue here is *still present* in latest version and being completely ignored, but I can't reopen it.

**Comment by theol0403** [comment]
I needed to run `git revert a47b508` to make the highlighting work in vi-mode. That pr seemed important, no idea why it was reverted. It makes this plugin a lot better for me.

**Comment by pushqrdx** [comment]
huh, didn't notice that it was reverted, been using and still using my PR on macOS and Linux since then without issues
